### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by macjeff** [rodtoll/smartthings-isy#2]
I have your homebridge plugin running and love it!!!

I want to link my smartthings in here.

So do I put all the device types as device handlers and the other as the smart app.

Just want to make sure I do this correctly.  I have added other smart apps so somewhat familiar.

Jeff

**Comment by jjslegacy** [comment]
Hey Jeff - I am trying to do the same thing but there seems to be a few key pieces of instructions left out.  It looks like Ron Barr did some work on it but I can't find a way to contact him.  Would be great if someone could explain exactly what is needed.

**Comment by macjeff** [comment]
I figured it out this morning.

Go to Ron Barr’s page on github and you will see he has a link to this (he did his own but abandoned it).  He has some updated versions of the smart app.

Here are basic instructions.  If you need more detailed I can do that.

1. Install the UPDATED smart app (called something like adds scenes)

2. Install all the device handlers you need.

3. Publish all of the above FOR ME

4. go into smart apps and my apps and choose this one.

5. Enter your ISY IP and Port #, ISY login and Password.   Then enter your smart things ip and port number and its login and password.

6. Then like magic within a few minute (time depends on how many devices) they all showed up!!!

Jeff

**Comment by jjslegacy** [comment]
Thanks Jeff - might be easier if we move to e-mail if you don't mind.   JJsLegacy at gmail.com

So for bridge info you entered your smartthings hub?  What port?

**Comment by macjeff** [comment]
3003 but if you want to use outside your home you have to port map 3003 through your router.

Jeff

**Comment by ocyberbum** [comment]
Hello, I am trying to get this working and i cant figure out why after i add everything from the code
https://github.com/rodtoll/smartthings-isy
The (ISY994IHUBSMARTAPP.groovy) App shows up on my SmartThings app or (ST app) where i can setup all my ISY/ST information to create the hub Device  but as soon as i do that the SmartThings app shows an error "Something's Wrong" under MY Home/Things and no devices shows up at all,  if i delete the device hub i created online under MY Locations/Devices manually then the SmartThings app shows devices again under MY Home/Things
Online my account shows everything i added and even some of my insteon devices but the smartThings  App will not show anything still, Any Help or Ideas would be appreciated
